plugins {
    id 'java'
}

group = 'com.horsefollow'
// version vem do gradle.properties (version=1.0.0)

repositories {
    mavenCentral()
}

dependencies {
    compileOnly files('libs/HytaleServer.jar')
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = 'UTF-8'
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    filteringCharset = 'UTF-8'

    // INJETA a versão no manifest.json durante o build
    filesMatching('manifest.json') {
        expand(modVersion: project.version.toString())
    }
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from('src/main/resources') {
        include 'manifest.json'
    }
    archiveFileName = "HorseFollow-${project.version}.jar"
}

